config/routes.rb
Rails.application.routes.draw do
  resources :regions
  resources :showcases
  resources :locations
  resources :users
  resources :feedbacks
  resources :songs
  resources :recordings
  resources :formations
  resources :solos
  resources :scores
  resources :heats
  resources :payments
  resources :answers
  resources :questions
  resources :tables
  resources :person_options
  resources :billables
  resources :judges
  resources :people do
    get "students", on: :collection
    get "backs", on: :collection
  end
  resources :events do
    get "summary", on: :collection
    get "publish", on: :collection
    get "settings", on: :collection
  end
  resources :entries
  resources :dances
  resources :cat_extensions
  resources :categories
  resources :studios do
    member do
      post :unpair
    end
  end
  resources :age_costs
  resources :ages
  resources :levels
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#root"
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :default_student_package, class_name: "Billable", optional: true
  belongs_to :default_professional_package, class_name: "Billable", optional: true
  belongs_to :default_guest_package, class_name: "Billable", optional: true

  has_many :people, dependent: :destroy

  has_many :studio1_pairs, class_name: "StudioPair", foreign_key: "studio2_id", dependent: :destroy
  has_many :studio1s, through: :studio1_pairs, source: :studio1, class_name: "Studio"
  has_many :studio2_pairs, class_name: "StudioPair", foreign_key: "studio1_id", dependent: :destroy
  has_many :studio2s, through: :studio2_pairs, source: :studio2, class_name: "Studio"

  normalizes :name, with: ->(name) { name.strip }

  scope :by_name, -> { order(:name) }

  validates :name, presence: true, uniqueness: true

  def pairs
    ids = studio1_pairs.pluck(:studio1_id) + studio2_pairs.pluck(:studio2_id)
    Studio.where(id: ids)
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: %i[ show edit update destroy unpair ]

  # GET /studios or /studios.json
  def index
    @studios = Studio.all.by_name
    @total_count = Person.where("studio_id is not null").count
  end

  # GET /studios/1 or /studios/1.json
  def show
  end

  # GET /studios/new
  def new
    @studio = Studio.new
    @pairs = []
    @avail = Studio.where.not(name: "Event Staff").pluck(:name)
  end

  # GET /studios/1/edit
  def edit
    @pairs = []
    @avail = Studio.where.not(name: [ "Event Staff", @studio.name ]).pluck(:name)
  end

  # POST /studios or /studios.json
  def create
    @studio = Studio.new(studio_params.except(:pair))

    respond_to do |format|
      if @studio.save
        add_pair
        format.html { redirect_to @studio, notice: "#{@studio.name} was successfully created." }
        format.json { render :show, status: :created, location: @studio }
      else
        @pairs = []
        @avail = Studio.where.not(name: "Event Staff").pluck(:name)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studios/1 or /studios/1.json
  def update
    respond_to do |format|
      if @studio.update(studio_params.except(:pair))
        add_pair
        format.html { redirect_to @studio, notice: "#{@studio.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @studio }
      else
        @pairs = []
        @avail = Studio.where.not(name: [ "Event Staff", @studio.name ]).pluck(:name)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studios/1 or /studios/1.json
  def destroy
    @studio.destroy

    respond_to do |format|
      format.html { redirect_to studios_url, status: 303, notice: "#{@studio.name} was successfully removed." }
      format.json { head :no_content }
    end
  end

  # POST /studios/1/unpair
  def unpair
    pair_name = params[:pair]
    pair_studio = Studio.find_by(name: pair_name)

    if pair_studio
      StudioPair.where(studio1: @studio, studio2: pair_studio)
        .or(StudioPair.where(studio1: pair_studio, studio2: @studio))
        .destroy_all
      redirect_to edit_studio_url(@studio), notice: "#{pair_studio.name} was successfully unpaired."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studio
      @studio = Studio.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def studio_params
      params.expect(studio: [ :name, :pair, :ballroom, :email, :heat_cost, :multi_cost, :solo_cost, :student_heat_cost, :student_multi_cost, :student_registration_cost, :student_solo_cost, :tables ])
    end

    def add_pair
      pair_name = params.dig(:studio, :pair)
      return if pair_name.blank?

      pair_studio = Studio.find_by(name: pair_name)
      return unless pair_studio

      StudioPair.find_or_create_by(studio1: @studio, studio2: pair_studio)
    end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/studios/_form.html.erb
<div data-controller="info-box">
  <div class="info-button">&#x24D8;</div>
  <ul class="info-box">
  <li>Pairing studios enable Students from one studio to dance with Professionals and Students from a neighboring studio.</li>
  <li>Pairs can be removed by hovering over the associated studio name and clicking on the Unpair button that appears.</li>
  <li>If prices are not overridden for the studio, the prices defined in the settings will apply.</li>
  <% if studio.id %>
  <li class="text-red-600 font-bold">Removing a studio will remove all professionals, guests, and students that are
  associated with the studio, and delete any heats and scores that have been entered for those individuals.
  <span class="font-normal">Any paired studios will no longer be paired with this studio, but will otherwise be
  unaffected.</span></li>
  <% end %>
  </ul>
</div>

<%= form_with(model: studio, class: "contents") do |form| %>
  <% if studio.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(studio.errors.count, "error") %> prohibited this studio from being saved:</h2>

      <ul>
        <% studio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% unless studio.id == 0 or avail.length == 0 %>
  <div class="my-5">
    <%= form.label 'pair'%>
    <%= form.select 'pair', avail, {include_blank: true},
      class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/studios/_studio.html.erb
<div id="<%= dom_id studio %>">
    <div class="flex justify-between items-center">
      <h1 class="mx-auto font-bold text-4xl pb-5"><%= studio.name %></h1>
    </div>

    <table class="table-fixed mx-auto">
    <thead>
      <tr>
        <td class="row-head">Name
        <td class="row-head">Type
        <% if studio.id > 0 %>
        <td class="row-head">Role
        <td class="row-head">Level
        <% end %>
      </tr>
    </thead>
    <tbody>
    <% studio.people.sort_by(&:name).each do |person| %>
      <tr>
        <td class="row-main"><%= link_to person.name, person %></td>
        <td class="row"><%= person.type %></td>
        <% if studio.id > 0 %>
        <td class="row"><%= person.role %></td>
        <td class="row"><%= person.level&.name %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
    </table>

  <% if action_name != "show" %>
    <%= link_to "Show this studio", studio, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this studio', edit_studio_path(studio), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/studios/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing studio</h1>

  <%= render "form", studio: @studio, avail: @avail %>

  <% unless @studio.id == 0 %>
  <%= button_to 'Remove this studio', studio_path(@studio), class: "btn-grey my-0",
    method: :delete, form: { class: "inline", data: { turbo_confirm: 'Are you sure?' }} %>
  <% end %>
  <%= link_to "Back to Studios", studios_path, class: "btn-green my-0" %>

  <% if @pairs and @pairs.size > 0 %>
  <h2 class="mt-8 font-bold text-2xl">Associated studios</h2>
  <ul class="list-disc list-inside">
  <% @pairs.sort_by {|studio| studio.name}.each do |pair| %>
  <li class="group flex">
    <span class="leading-8 mr-4">&bull;&nbsp;<%= pair.name %></span>
    <form method="post" action="<%= unpair_studio_path(@studio) %>">
    <input type="hidden" name="pair" value="<%= pair.name %>">
    <button type="submit" class='group-hover:inline hidden x-2 rounded-lg py-1 px-2 text-white bg-red-600 font-medium'>Unpair</button>
    </form>
  </li>
  <% end %>
  </ul>
  <% end %>
  </div>

</div>

app/views/studios/index.html.erb
<div class="mx-auto">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div data-controller="info-box">
    <div class="info-button">&#x24D8;</div>
    <ul class="info-box">
      <li>Studios are the primary organizational unit for managing participants at your event.
      <li>Click on a studio name to view details and add people (Professionals, Guests, Students) to that studio.
      <li>The Count column shows the total number of people associated with each studio.
      <li>Use "New studio" to add a participating studio. Studios can be paired to enable cross-studio dancing.
    </ul>
  </div>

  <div class="flex justify-between items-center">
    <h1 class="mx-auto font-bold text-4xl pb-5">Studios</h1>
  </div>

  <div id="studios" class="min-w-full">
    <table class="table-fixed mx-auto">
    <thead>
      <tr>
        <td class="row-head">Location</td>
        <td class="row-head">Count</td>
      </tr>
    </thead>
    <tbody>
    <% @studios.each do |studio| %>
      <tr>
        <td class="text-black font-medium"><%= link_to studio.name, studio %></td>
        <td class="text-right"><%= studio.people.count %></td>
      </tr>
    <% end %>
      <tr>
        <th class="row-foot-right">totals</th>
        <td class="row-foot-right"><%= @total_count %></td>
      </tr>
    </tbody>
    </table>
  </div>

  <div class="mt-4 flex justify-between items-center">
    <%= link_to 'New studio', new_studio_path, class: "btn-blue" %>
    <div class="flex gap-2">
      <%= link_to "Back to Event", root_path, class: "btn-green" %>
    </div>
  </div>
</div>

app/views/studios/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New studio</h1>

  <%= render "form", studio: @studio, avail: @avail %>

  <%= link_to "Back to Studios", studios_path, class: "btn-green my-0" %>
</div>

app/views/studios/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div data-controller="info-box">
      <div class="info-button">&#x24D8;</div>
      <ul class="info-box">
        <li>Use "Add Person" to add Professionals, Guests, or Students to this studio.
        <li>Click "Edit this studio" to change name, pair with another studio, or set pricing overrides.
      </ul>
    </div>

    <%= render @studio %>

    <div class="mt-8 grid grid-cols-3 gap-1">
      <%= link_to 'Add Person', new_person_path(studio: @studio), class: "btn-blue" %>
      <%= link_to 'Edit this studio', edit_studio_path(@studio), class: "btn-grey" %>
      <%= link_to 'Back to Studios', studios_path, class: "btn-green" %>
    </div>
  </div>
</div>